server:
  port: 9070

spring:
  application:
    name: rdbms-sensing
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      interceptor.classes: io.wisoft.eventsourcing.rdbms.query.interceptor.KafkaConsumerInterceptor
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5434/nrf_sensing_query
    username: charlie
    password: DBLab1004**
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true



axon:
  serializer:
    general: xstream
  axonserver:
    servers: ${AXON_HOST:localhost}:8124

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    io.wisoft.eventsourcing.rdbms.query: debug
    org.axonframework: debug
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF


